name: Angular CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./autowatererfrontend
    
    strategy:
      matrix:
        node-version: [20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
    
    - name: Setup Nodejs
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm run test:ci
    - name: Build
      run: npm run build --if-present
